spring.application.name=backend
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskloom}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:sd2003}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.default_schema=taskloom
spring.sql.init.mode=always

jwt.secret=${JWT_SECRET:taskloom-secret-key-taskloom-secret-key}
cors.allowed-origin=${CORS_ORIGIN:http://localhost:3000}

server.port=8080